export const cssPropsExample = {
  "alignContent": "center",
  "alignItems": "center",
  "alignSelf": "center",
  "animation": "myAnimation 2s linear",
  "animationDelay": "2s",
  "animationDirection": "alternate",
  "animationDuration": "2s",
  "animationFillMode": "forwards",
  "animationIterationCount": "3",
  "animationName": "myAnimation",
  "animationPlayState": "paused",
  "animationTimingFunction": "linear",
  "backfaceVisibility": "hidden",
  "background": "red",
  "backgroundAttachment": "fixed",
  "backgroundClip": "border-box",
  "backgroundColor": "red",
  "backgroundImage": "url(\"https://example.com/image.png\")",
  "backgroundOrigin": "padding-box",
  "backgroundPosition": "0 0",
  "backgroundRepeat": "repeat",
  "backgroundSize": "cover",
  "blockSize": "50px",
  "border": "1px solid black",
  "borderBlockEnd": "1px solid black",
  "borderBlockEndColor": "red",
  "borderBlockEndStyle": "solid",
  "borderBlockEndWidth": "1px",
  "borderBlockStart": "1px solid black",
  "borderBlockStartColor": "red",
  "borderBlockStartStyle": "solid",
  "borderBlockStartWidth": "1px",
  "borderBottom": "1px solid black",
  "borderBottomColor": "red",
  "borderBottomLeftRadius": "5px",
  "borderBottomRightRadius": "5px",
  "borderBottomStyle": "solid",
  "borderBottomWidth": "1px",
  "borderCollapse": "collapse",
  "borderColor": "red",
  "borderImage": "url(\"https://example.com/image.png\") 30 30 round round",
  "borderImageOutset": "10px",
  "borderImageRepeat": "round round",
  "borderImageSlice": "30 30",
  "borderImageSource": "url(\"https://example.com/image.png\")",
  "borderImageWidth": "30px",
  "borderInlineEnd": "1px solid black",
  "borderInlineEndColor": "red",
  "borderInlineEndStyle": "solid",
  "borderInlineEndWidth": "1px",
  "borderInlineStart": "1px solid black",
  "borderInlineStartColor": "red",
  "borderInlineStartStyle": "solid",
  "borderInlineStartWidth": "1px",
  "borderLeft": "1px solid black",
  "borderLeftColor": "red",
  "borderLeftStyle": "solid",
  "borderLeftWidth": "1px",
  "borderRadius": "5px",
  "borderRight": "1px solid black",
  "borderRightColor": "red",
  "borderRightStyle": "solid",
  "borderRightWidth": "1px",
  "borderSpacing": "10px",
  "borderStyle": "solid",
  "borderTop": "1px solid black",
  "borderTopColor": "red",
  "borderTopLeftRadius": "5px",
  "borderTopRightRadius": "5px",
  "borderTopStyle": "solid",
  "borderTopWidth": "1px",
  "borderWidth": "1px",
  "bottom": "10px",
  "boxDecorationBreak": "slice",
  "boxShadow": "10px 10px 5px 0px rgba(0,0,0,0.75)",
  "boxSizing": "border-box",
  "breakAfter": "always",
  "breakBefore": "always",
  "breakInside": "avoid",
  "captionSide": "top",
  "caretColor": "red",
  "clear": "both",
  "clip": "rect(0 0 0 0)",
  "clipPath": "url(\"#myClip\")",
  "color": "red",
  "columnCount": "3",
  "columnFill": "balance",
  "columnGap": "10px",
  "columnRule": "1px solid black",
  "columnRuleColor": "red",
  "columnRuleStyle": "solid",
  "columnRuleWidth": "1px",
  "columnSpan": "2",
  "columnWidth": "100px",
  "columns": "100px 3",
  "content": "\"\"",
  "counterIncrement": "myCounter",
  "counterReset": "myCounter",
  "cursor": "pointer",
  "direction": "ltr",
  "display": "block",
  "emptyCells": "show",
  "filter": "blur(5px)",
  "flex": "1 1 auto",
  "flexBasis": "auto",
  "flexDirection": "row",
  "flexFlow": "row wrap",
  "flexGrow": "0",
  "flexShrink": "1",
  "flexWrap": "wrap",
  "float": "left",
  "font": "400 16px/1.8 Arial, sans-serif",
  "fontFamily": "Arial, sans-serif",
  "fontFeatureSettings": "normal",
  "fontKerning": "auto",
  "fontLanguageOverride": "normal",
  "fontSize": "16px",
  "fontSizeAdjust": "none",
  "fontStretch": "normal",
  "fontStyle": "normal",
  "fontSynthesis": "weight style",
  "fontVariant": "normal",
  "fontVariantAlternates": "normal",
  "fontVariantCaps": "normal",
  "fontVariantEastAsian": "normal",
  "fontVariantLigatures": "normal",
  "fontVariantNumeric": "normal",
  "fontVariantPosition": "normal",
  "fontWeight": "400",
  "grid": "auto / auto",
  "gridArea": "header",
  "gridAutoColumns": "auto",
  "gridAutoFlow": "row",
  "gridAutoRows": "auto",
  "gridColumn": "span 2",
  "gridColumnEnd": "span 2",
  "gridColumnGap": "10px",
  "gridColumnStart": "span 2",
  "gridGap": "10px",
  "gridRow": "span 2",
  "gridRowEnd": "span 2",
  "gridRowGap": "10px",
  "gridRowStart": "span 2",
  "gridTemplate": "auto / auto",
  "gridTemplateAreas": "\"header header header\" \"sidebar main main\" \"footer footer footer\"",
  "gridTemplateColumns": "auto auto auto",
  "gridTemplateRows": "auto auto auto",
  "height": "100px",
  "hyphens": "auto",
  "imageOrientation": "from-image",
  "imageRendering": "auto",
  "imageResolution": "normal",
  "imeMode": "normal",
  "inlineSize": "100px",
  "isolation": "isolate",
  "justifyContent": "center",
  "justifyItems": "center",
  "justifySelf": "center",
  "letterSpacing": "1px",
  "lineBreak": "auto",
  "lineHeight": "1.8",
  "listStyle": "disc outside none",
  "listStyleImage": "url(\"https://example.com/image.png\")",
  "listStylePosition": "outside",
  "listStyleType": "disc",
  "margin": "10px",
  "marginBlockEnd": "10px",
  "marginBlockStart": "10px",
  "marginBottom": "10px",
  "marginInlineEnd": "10px",
  "marginInlineStart": "10px",
  "marginLeft": "10px",
  "marginRight": "10px",
  "marginTop": "10px",
  "mask": "url(\"#myMask\")",
  "maskClip": "border-box",
  "maskComposite": "add",
  "maskImage": "url(\"https://example.com/image.png\")",
  "maskMode": "match-source",
  "maskOrigin": "border-box",
  "maskPosition": "0 0",
  "maskRepeat": "repeat",
  "maskSize": "50px 50px",
  "maskType": "alpha",
  "maxBlockSize": "50px",
  "maxHeight": "100px",
  "maxInlineSize": "50px",
  "maxWidth": "100px",
  "minBlockSize": "50px",
  "minHeight": "100px",
  "minInlineSize": "50px",
  "minWidth": "100px",
  "mixBlendMode": "normal",
  "objectFit": "fill",
  "objectPosition": "50% 50%",
  "offset": "10px 20px",
  "offsetAnchor": "10px 20px",
  "offsetBlockEnd": "10px",
  "offsetBlockStart": "10px",
  "offsetInlineEnd": "10px",
  "offsetInlineStart": "10px",
  "offsetDistance": "10px",
  "offsetPath": "path(\"M10 10H90V90H10L10 10\")",
  "offsetPosition": "10px",
  "offsetRotate": "auto 0deg",
  "opacity": "0.5",
  "order": "1",
  "orphans": "2",
  "outline": "1px solid black",
  "outlineColor": "red",
  "outlineOffset": "10px",
  "outlineStyle": "solid",
  "outlineWidth": "1px",
  "overflow": "visible",
  "overflowAnchor": "visible",
  "overflowBlock": "visible",
  "overflowInline": "visible",
  "overflowWrap": "normal",
  "overflowX": "visible",
  "overflowY": "visible",
  "padding": "10px",
  "paddingBlockEnd": "10px",
  "paddingBlockStart": "10px",
  "paddingBottom": "10px",
  "paddingInlineEnd": "10px",
  "paddingInlineStart": "10px",
  "paddingLeft": "10px",
  "paddingRight": "10px",
  "paddingTop": "10px",
  "pageBreakAfter": "always",
  "pageBreakBefore": "always",
  "pageBreakInside": "avoid",
  "paintOrder": "normal",
  "perspective": "1000px",
  "perspectiveOrigin": "50% 50%",
  "pointerEvents": "auto",
  "position": "static",
  "quotes": "\"\" \"\"",
  "resize": "none",
  "right": "10px",
  "rotate": "10deg",
  "rowGap": "10px",
  "scale": "1",
  "scrollBehavior": "smooth",
  "scrollSnapCoordinate": "none",
  "scrollSnapDestination": "0px 0px",
  "scrollSnapPointsX": "none",
  "scrollSnapPointsY": "none",
  "scrollSnapType": "none",
  "scrollSnapTypeX": "none",
  "scrollSnapTypeY": "none",
  "shapeImageThreshold": "0",
  "shapeMargin": "0",
  "shapeOutside": "none",
  "tableLayout": "auto",
  "tabSize": "4",
  "textAlign": "center",
  "textAlignLast": "justify",
  "textAnchor": "middle",
  "textCombineUpright": "none",
  "textDecoration": "underline",
  "textDecorationColor": "red",
  "textDecorationLine": "underline",
  "textDecorationSkip": "objects",
  "textDecorationStyle": "solid",
  "textIndent": "10px",
  "textOrientation": "mixed",
  "textOverflow": "clip",
  "textRendering": "auto",
  "textShadow": "10px 10px 5px red",
  "textTransform": "uppercase",
  "textUnderlinePosition": "auto",
  "top": "10px",
  "touchAction": "none",
  "transform": "translate(10px, 10px)",
  "transformBox": "view-box",
  "transformOrigin": "50% 50%",
  "transformStyle": "flat",
  "transition": "all 2s linear",
  "transitionDelay": "2s",
  "transitionDuration": "2s",
  "transitionProperty": "all",
  "transitionTimingFunction": "linear",
  "unicodeBidi": "normal",
  "userSelect": "none",
  "verticalAlign": "middle",
  "visibility": "visible",
  "whiteSpace": "normal",
  "widows": "2",
  "width": "100px",
  "willChange": "auto",
  "wordBreak": "normal",
  "wordSpacing": "1px",
  "wordWrap": "normal",
  "writingMode": "horizontal-tb",
  "zIndex": "auto"
}
export const cssAcceptsPixels = {
  "alignContent": false,
  "alignItems": false,
  "alignSelf": false,
  "alignmentBaseline": false,
  "all": false,
  "animation": false,
  "animationDelay": false,
  "animationDirection": false,
  "animationDuration": false,
  "animationFillMode": false,
  "animationIterationCount": false,
  "animationName": false,
  "animationPlayState": false,
  "animationTimingFunction": false,
  "backfaceVisibility": false,
  "background": false,
  "backgroundAttachment": false,
  "backgroundClip": false,
  "backgroundColor": true,
  "backgroundImage": false,
  "backgroundOrigin": false,
  "backgroundPosition": true,
  "backgroundPositionX": true,
  "backgroundPositionY": true,
  "backgroundRepeat": false,
  "backgroundSize": false,
  "baselineShift": false,
  "border": false,
  "borderBottom": false,
  "borderBottomColor": true,
  "borderBottomLeftRadius": true,
  "borderBottomRightRadius": true,
  "borderBottomStyle": false,
  "borderBottomWidth": true,
  "borderCollapse": false,
  "borderColor": true,
  "borderImage": false,
  "borderImageOutset": false,
  "borderImageRepeat": false,
  "borderImageSlice": false,
  "borderImageSource": false,
  "borderImageWidth": false,
  "borderLeft": false,
  "borderLeftColor": true,
  "borderLeftStyle": false,
  "borderLeftWidth": true,
  "borderRadius": true,
  "borderRight": false,
  "borderRightColor": true,
  "borderRightStyle": false,
  "borderRightWidth": true,
  "borderSpacing": false,
  "borderStyle": false,
  "borderTop": false,
  "borderTopColor": true,
  "borderTopLeftRadius": true,
  "borderTopRightRadius": true,
  "borderTopStyle": false,
  "borderTopWidth": true,
  "borderWidth": true,
  "bottom": true,
  "boxShadow": false,
  "boxSizing": false,
  "breakAfter": false,
  "breakBefore": false,
  "breakInside": false,
  "bufferedRendering": false,
  "captionSide": false,
  "clear": false,
  "clip": false,
  "clipPath": false,
  "clipRule": false,
  "color": true,
  "colorInterpolation": false,
  "colorInterpolationFilters": false,
  "colorProfile": false,
  "colorRendering": false,
  "columnCount": false,
  "columnFill": false,
  "columnGap": false,
  "columnRule": false,
  "columnRuleColor": true,
  "columnRuleStyle": false,
  "columnRuleWidth": true,
  "columnSpan": false,
  "columnWidth": false,
  "columns": false,
  "content": false,
  "counterIncrement": false,
  "counterReset": false,
  "cursor": false,
  "direction": false,
  "display": false,
  "dominantBaseline": false,
  "emptyCells": false,
  "enableBackground": false,
  "fill": false,
  "fillOpacity": true,
  "fillRule": false,
  "filter": false,
  "flex": false,
  "flexBasis": true,
  "flexDirection": false,
  "flexFlow": false,
  "flexGrow": true,
  "flexShrink": true,
  "flexWrap": false,
  "floodColor": true,
  "floodOpacity": false,
  "font": false,
  "fontFamily": false,
  "fontSize": true,
  "fontStretch": false,
  "fontStyle": false,
  "fontVariant": false,
  "fontWeight": false,
  "glyphOrientationHorizontal": false,
  "glyphOrientationVertical": false,
  "height": true,
  "imageRendering": false,
  "kerning": true,
  "left": true,
  "letterSpacing": true,
  "lightingColor": true,
  "lineHeight": true,
  "listStyle": false,
  "listStyleImage": false,
  "listStylePosition": false,
  "listStyleType": false,
  "margin": true,
  "marginBottom": true,
  "marginLeft": true,
  "marginRight": true,
  "marginTop": true,
  "marker": false,
  "markerEnd": false,
  "markerMid": false,
  "markerStart": false,
  "mask": false,
  "maxHeight": true,
  "maxWidth": true,
  "minHeight": true,
  "minWidth": true,
  "opacity": true,
  "order": true,
  "orphans": false,
  "outline": false,
  "outlineColor": true,
  "outlineOffset": true,
  "outlineStyle": false,
  "outlineWidth": true,
  "overflow": false,
  "overflowWrap": false,
  "overflowX": false,
  "overflowY": false,
  "padding": true,
  "paddingBottom": true,
  "paddingLeft": true,
  "paddingRight": true,
  "paddingTop": true,
  "pageBreakAfter": false,
  "pageBreakBefore": false,
  "pageBreakInside": false,
  "pointerEvents": false,
  "position": false,
  "quotes": false,
  "resize": false,
  "right": true,
  "shapeRendering": false,
  "size": false,
  "speak": false,
  "src": false,
  "stopColor": true,
  "stopOpacity": true,
  "stroke": false,
  "strokeDasharray": false,
  "strokeDashoffset": true,
  "strokeLinecap": false,
  "strokeLinejoin": false,
  "strokeMiterlimit": true,
  "strokeOpacity": true,
  "strokeWidth": true,
  "tableLayout": false,
  "textAlign": false,
  "textAnchor": false,
  "textDecoration": false,
  "textIndent": true,
  "textLineThrough": false,
  "textLineThroughColor": true,
  "textLineThroughMode": false,
  "textLineThroughStyle": false,
  "textLineThroughWidth": true,
  "textOverflow": false,
  "textOverline": false,
  "textOverlineColor": true,
  "textOverlineMode": false,
  "textOverlineStyle": false,
  "textOverlineWidth": true,
  "textRendering": false,
  "textShadow": false,
  "textTransform": false,
  "textUnderline": false,
  "textUnderlineColor": true,
  "textUnderlineMode": false,
  "textUnderlineStyle": false,
  "textUnderlineWidth": true,
  "top": true,
  "unicodeBidi": false,
  "unicodeRange": false,
  "userSelect": false,
  "vectorEffect": false,
  "verticalAlign": true,
  "visibility": false,
  "whiteSpace": false,
  "widows": false,
  "width": true,
  "wordBreak": false,
  "wordSpacing": true,
  "wordWrap": false,
  "writingMode": false,
  "zIndex": true,
  "zoom": true
}