export * from './BaseSchema'
export * from './ProtoModel'
export * from './ProtoCollection'
export * from './ProtoSchema'
export * from './PendingResult'
export * from './env'
export * from './Api'
export * from './lib/isElectron'
export * from './logger'
export const Protofy = (type, x)=> x;