export type EditableObjectProps = {
    initialData?: any,
    sourceUrl?: string,
    onSave?: Function,
    model: any,
    mode?: 'add' | 'edit' | 'view' | 'preview',
    icons?: any,
    extraFields?: any,
    numColumns?: number,
    objectId?: string,
    title?: any,
    loadingText?: any,
    loadingTop?: number,
    spinnerSize?: number,
    name?: string,
    customFields?: any,
    columnWidth?: number,
    disableToggleMode?: boolean,
    columnMargin?: number,
    onDelete?: Function,
    deleteable?: Function,
    autoWidth?: Boolean,
    extraMenuActions?: any[],
    data?: any,
    setData?: Function,
    error?: any,
    setError?: Function,
    externalErrorHandling?: Boolean,
    URLTransform?: Function,
    disableAutoChangeMode?: Boolean
}