version: '2'
services:
  chrome:
    image: selenium/node-chrome:4.16.1-20231212
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "6900:5900"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  selenium-hub:
    image: selenium/hub:4.16.1-20231212
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    extra_hosts:
      - "host.docker.internal:host-gateway"